LoopOptions::gpu_block_index(): bool -> int (#37578)
Summary:
Small change to allow MSVC build pass.
The error is

```
D:\pytorch-scripts\caffe2_builders\v141\pytorch\torch/csrc/jit/tensorexpr/stmt.h(370): error C4805: '!=': unsafe mix
of type 'bool' and type 'int' in operation (compiling source file D:\pytorch-scripts\caffe2_builders\v141\pytorch\torch
\csrc\jit\passes\tensorexpr_fuser.cpp) [D:\pytorch-scripts\caffe2_builders\v141\pytorch\build\RelWithDebInfo\caffe2\tor
ch_cpu.vcxproj]
```
Pull Request resolved: https://github.com/pytorch/pytorch/pull/37578

Differential Revision: D21348964

Pulled By: ezyang

fbshipit-source-id: 2c5f995e0adbeb681c18625b59250d7ee3e958ef