Add hpu to fused kernels supported devices (#89)
Merged counterpart in Upstream:
https://github.com/pytorch/pytorch/pull/148666

This change adds "hpu" to the list of device types that support fused kernels in the optimizer, ensuring
compatibility with HPU backend.

Without this change, when test_all_gather_extension_outer_size_stride of pytorch/test/distributed/_composable/fsdp/test_fully_shard_extensions.py is run on 'hpu' backend, it fails with:

RuntimeError: fused=True requires all the params to be floating point Tensors
of supported devices: ['mps', 'cuda', 'xpu', 'cpu', 'privateuseone']
but torch.float32 and hpu