Revert "Support masked_fill (#88736)"
This reverts commit 2b131b1d43b10a2a005f3f042f920a62501e4e2d.

Reverted https://github.com/pytorch/pytorch/pull/88736 on behalf of https://github.com/kit1980 due to Inductor tests are failing with AttributeError: module 'torch._inductor.codecache' has no attribute 'valid_vec_isa_list'